blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    about: For broader discussions, questions, or general feedback...
    url: https://github.com/tpvasconcelos/ridgeplot/discussions
